<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "falgallery"
 *
 * Auto generated by Extension Builder 2014-09-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FAL Gallery',
	'description' => 'Displays galleries from file collection that base on FAL images or FAL categories.',
	'category' => 'plugin',
	'author' => 'Lorenz Ulrich, David Janssen',
	'author_email' => 'lorenz.ulrich@phlu.ch, david.janssen@phlu.ch',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);